### ISSUE TITLE
jackstraw

### ISSUE THREAD

**Issue by ajbass** [StoreyLab/edge#11]
```
> ## apply the jackstraw
> out = apply_jackstraw(de_obj, r1=1, r=1)
Error: 'jackstraw.PCA' is not an exported object from 'namespace:jackstraw'
```

@ncchung is it ```jackstraw_pca``` now? any other changes I should put in? 

Cheers,
Andy 

PS: Hope everything is going well!

**Comment by ncchung** [comment]
Hi Andy,

Yes, please use `jackstraw_pca`.

I'm trying to revamp the jackstraw package to be more versatile :)  Right now, on the development/Github version, there is `jackstraw_rpca` and `jackstraw_irlba` for faster (approximate) computation. Also in the near future, I'll implement a support for multicores. There's a new set of jackstraw functions for clustering, such as `jackstraw_kmeans`, `jackstraw_pam` and `jackstraw_MiniBatchKmeans`. I'd be happy to incorporate them in the edge package. 

Keep it up Andy!

**Comment by ajbass** [comment]
Awesome! I think it would be easier if you edit the function to add the features you want users to use? I can take care of the debugging after.

**Comment by ncchung** [comment]
I changed `jackstraw.PCA` to `jackstraw_pca` (reflecting the change in the jackstraw package v1.2).

I'll add other features (planned for the jackstraw package v1.3+) to the edge package in the future.
