### ISSUE TITLE
Error in smooth.spline(lambda, pi0, df = smooth.df) : missing or infinite values in inputs are not allowed

### ISSUE THREAD

**Issue by reventropy** [StoreyLab/edge#13]
Hello,

I'm analyzing a time series proteomics data set. Missing values necessitate that I run Edge on subsets of the data so that I have consistent replicates for each time point. Edge is failing on one of these subsets but I cannot figure out why. There are no -inf,inf of nan values in either the expression data or in the de_obj. I've attached the de_obj data frame if that helps.  Any suggestions would be great.  Thanks!

[0_2.txt](https://github.com/StoreyLab/edge/files/2342897/0_2.txt)

Thanks,

Jeremy Jacobsen
PRA, University of Colorado, Boulder

**Comment by ajbass** [comment]
Hi Jeremy-

Can you also include the code you used to get the error? 

Thanks, 
Andrew

**Comment by reventropy** [comment]
Hi ajbass,

I run the same code (below) on all subsets.  It works fine for most data subsets, but not for this one.  I perform a BH correction externally after all subsets are processed, so I'm only using edge to calculate p-values.  It's failing on the likelihood ratio test.  I've also tried odp with the same result.  Thanks again.



```
ind <- data.matrix(read.table(paste(rootpath,"indices.csv",sep=""),sep=",",header = T))
class <- factor(data.matrix(read.table(paste(rootpath,"class.csv",sep=""),sep=",",header = T)))
time <- data.matrix(read.table(paste(rootpath,"time.csv",sep=""),sep=",",header = T))
expr <- data.matrix(read.table(paste(rootpath,"Expr.csv",sep=""),sep=",",header = F))
colnames(expr) <- NULL

de_obj <- build_study(data = expr, grp = class, tme = time, ind = ind, sampling = "timecourse")
de_lrt <- lrt(de_obj)  ##<- failing here
pvals = slot(de_lrt,"qvalueObj")$pvalues

```

**Comment by ajbass** [comment]
So ```edge``` automatically applies the ```qvalue``` function to the p-values, which requires a few hundred genes to estimate pi0 accurately. The dataset you attached only has 54 rows .... I suspect this is where the error occurs.

 One thing you can do is use the ```pi0 = 1``` argument in ```qvalue``` to force the BH procedure to be used. This avoids estimating pi0 from the data.  Does this work: ```de_lrt <- lrt(de_obj, pi0 = 1)```? You should now be able to grab the unadjusted p-values using the code you posted.

**Comment by reventropy** [comment]
Thank you so much!  This appears to fix the issue so I'm calling it closed.

**Comment by Zepeng-Mu** [comment]
Hi, I also got the same error when I was trying to apply the function to my QTL mapping data with >10000 genes. What could be the possible reason for the error?
Thanks

**Comment by ajbass** [comment]
Can you try:

```
de_lrt <- lrt(de_obj, pi0 = 1)
hist(p)
max(p)
```

Are nearly all of your p-values significant? If so, this is an error message from qvalue and I recommend running it with `pi0=1` to force the BH procedure to be run.

**Comment by Zepeng-Mu** [comment]
Hi, so I tried. There is no error when using `pi0=1`, and I indeed have a majority of significant p-values, I also saw another issue discussing this problem just now. I guess I can use a permutation-based p-value as input to get a better distribution of p-values.
Thank you so much!
