### ISSUE TITLE
Number of significant features is larger when viewing the obtained q-values, compared to that of p-value

### ISSUE THREAD

**Issue by Payamdel** [StoreyLab/edge#14]
I have noticed that ,it some cases, number of significant genes/features at various cutoffs are more pronounced (larger) in terms of q-values than the corresponding p-values when viewing the Cumulative number of significant calls. I suppose that the number of significant genes in terms of q-values should be equal or less pronounced when compared to its corresponding p-value?  Isn't so?
On page 13 of [https://bioconductor.org/packages/release/bioc/vignettes/edge/inst/doc/edge.pdf] one can see the example.
Any thoughts on that?

**Comment by ajbass** [comment]
It is possible to get q-values smaller than p-values: (i) small proportion of true nulls and (ii) you have a lot of power in your study.  

Heres an artificial example:

```
library(qvalue)
set.seed(12345)
pvalues <- c(runif(400, .00001, 0.0005), runif(200, 0,1)) #(alternative pvalues, null pvalues) 
summary(qvalue(pvalues))
```
