### ISSUE TITLE
Error when using opd function

### ISSUE THREAD

**Issue by harryscholes** [StoreyLab/edge#9]
I am trying to identify differentially expressed genes from my longitudinal time course experiment. I am following the guide in chapter 7 of the [manual](https://www.bioconductor.org/packages/devel/bioc/vignettes/edge/inst/doc/edge.pdf).

I am able to perform the likelihood ratio test using `de_lrt <- lrt(de_obj, nullDistn = "normal")`. However, when I perform the optimal discovery procedure, I receive the following error:

```
de_odp <- odp(de_obj)
Null iteration:  1
Error in odp.score(s.dat0, mu = rep(0, length(clustParms$sig.null)), sigma = clustParms$sig.null,  : NA/NaN/Inf in foreign function call (arg 1)
```

I have double checked and none of my data passed to `build_study` contains `NA`, `NaN` or `Inf`. Do you know how to resolve this issue?

**Comment by ajbass** [comment]
The issue is not immediately clear to me:

(1) What is the dimension of your expression matrix and design matrix?

(2) Do you get an error when you run `lrt` as follows:

```
de_lrt <- lrt(de_obj, nullDistn = "bootstrap")
```

(3) Can you show me the results from lrt:

```
summary(qvalueObj(de_lrt))
```

Cheers

**Comment by harryscholes** [comment]
Thanks for your speedy reply.

(1) Expression matrix:
```
> dim(expression_matrix)
[1] 1854   82
```

(2) I do get an error after all of the bootstrap iterations have completed:

```
> lrt(de_obj, nullDistn = "bootstrap")
 Null iteration:  100
Error in pi0est(p, ...) : 
  ERROR: The estimated pi0 <= 0. Check that you have valid p-values or use a different range of lambda.
```

(3) Summary:

```
> summary(qvalueObj(de_lrt))

Call:
qvalue(p = pval)

pi0:	0.3559572	

Cumulative number of significant calls:

          <1e-04 <0.001 <0.01 <0.025 <0.05 <0.1   <1
p-value       32     93   231    349   497  678 1854
q-value        6     21   112    213   386  689 1854
local FDR      5     12    70    122   197  348 1854
```

Hope this helps! I could also share the input data with you if necessary.

**Comment by ajbass** [comment]
One other question: What about your design matrix? (full and null model) What are the dimensions/experimental design? This could have something to do with the residuals from the model fit (could be worth looking at the residuals using the function `fit_models`), such that when it is bootstrapping to determine the null distribution something funky happens.

**Comment by harryscholes** [comment]
Do you mean the dimensions of the full and null matrices?

```
> de_obj <- build_study(data = df, grp = class,
+                       tme = time, ind = ind, sampling = "timecourse")
> 
> fullModel(de_obj)
~grp + ns(tme, df = 2, intercept = FALSE) + (grp):ns(tme, df = 2, 
    intercept = FALSE)
<environment: 0x203d57e98>
> nullModel(de_obj)
~grp + ns(tme, df = 2, intercept = FALSE)
<environment: 0x203d57e98>
> 
> full_matrix <- fullMatrix(de_obj)
> null_matrix <- nullMatrix(de_obj)
> dim(full_matrix)
[1] 82  6
> dim(null_matrix)
[1] 82  4
```

What should I be looking out for in the residuals matrix produced by `fit_models`? I have attached the residuals matrices in case you can spot anything in them.

[residuals.zip](https://github.com/StoreyLab/edge/files/1410150/residuals.zip)

Many thanks for your help 😃
